/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as QuestionBankRouteImport } from './routes/question-bank'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as CustomQuestionsRouteImport } from './routes/custom-questions'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionBankBankIdRouteImport } from './routes/question-bank.$bankId'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRoute = QuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomQuestionsRoute = CustomQuestionsRouteImport.update({
  id: '/custom-questions',
  path: '/custom-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankBankIdRoute = QuestionBankBankIdRouteImport.update({
  id: '/$bankId',
  path: '/$bankId',
  getParentRoute: () => QuestionBankRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banks': typeof BanksRoute
  '/custom-questions': typeof CustomQuestionsRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/question-bank': typeof QuestionBankRouteWithChildren
  '/writing': typeof WritingRoute
  '/question-bank/$bankId': typeof QuestionBankBankIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banks': typeof BanksRoute
  '/custom-questions': typeof CustomQuestionsRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/question-bank': typeof QuestionBankRouteWithChildren
  '/writing': typeof WritingRoute
  '/question-bank/$bankId': typeof QuestionBankBankIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banks': typeof BanksRoute
  '/custom-questions': typeof CustomQuestionsRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/question-bank': typeof QuestionBankRouteWithChildren
  '/writing': typeof WritingRoute
  '/question-bank/$bankId': typeof QuestionBankBankIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/banks'
    | '/custom-questions'
    | '/mistakes'
    | '/practice'
    | '/pricing'
    | '/question-bank'
    | '/writing'
    | '/question-bank/$bankId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/banks'
    | '/custom-questions'
    | '/mistakes'
    | '/practice'
    | '/pricing'
    | '/question-bank'
    | '/writing'
    | '/question-bank/$bankId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/banks'
    | '/custom-questions'
    | '/mistakes'
    | '/practice'
    | '/pricing'
    | '/question-bank'
    | '/writing'
    | '/question-bank/$bankId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BanksRoute: typeof BanksRoute
  CustomQuestionsRoute: typeof CustomQuestionsRoute
  MistakesRoute: typeof MistakesRoute
  PracticeRoute: typeof PracticeRoute
  PricingRoute: typeof PricingRoute
  QuestionBankRoute: typeof QuestionBankRouteWithChildren
  WritingRoute: typeof WritingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-questions': {
      id: '/custom-questions'
      path: '/custom-questions'
      fullPath: '/custom-questions'
      preLoaderRoute: typeof CustomQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank/$bankId': {
      id: '/question-bank/$bankId'
      path: '/$bankId'
      fullPath: '/question-bank/$bankId'
      preLoaderRoute: typeof QuestionBankBankIdRouteImport
      parentRoute: typeof QuestionBankRoute
    }
  }
}

interface QuestionBankRouteChildren {
  QuestionBankBankIdRoute: typeof QuestionBankBankIdRoute
}

const QuestionBankRouteChildren: QuestionBankRouteChildren = {
  QuestionBankBankIdRoute: QuestionBankBankIdRoute,
}

const QuestionBankRouteWithChildren = QuestionBankRoute._addFileChildren(
  QuestionBankRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BanksRoute: BanksRoute,
  CustomQuestionsRoute: CustomQuestionsRoute,
  MistakesRoute: MistakesRoute,
  PracticeRoute: PracticeRoute,
  PricingRoute: PricingRoute,
  QuestionBankRoute: QuestionBankRouteWithChildren,
  WritingRoute: WritingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
